RoIHeads: remove low-scoring boxes statically
One of the postprocessing step of RoIHeads is to filter low-scoring (in
terms of confidence level) boxes from the output. This commit makes that
operation static for TPUs.

For now, it's needed to make it static manually as the experimental
support for dynamic nonzero/masked_select would raise the following
issue in this case:

RuntimeError: Internal: From /job:tpu_worker/replica:0/task:0:
RET_CHECK failure (learning/brain/google/xla/tpu_execute.cc:1066) size >= 0
	 [[{{node XRTExecute}}]]